### PR TITLE
Create ambstrong.cpp

### PR DESCRIPTION
**Pull request by ujjwalshiva**

### CODE REVIEW

**Comment by khawajaazfar2000** [comment]
You copy from geek for geeks?

**Comment by ujjwalshiva** [comment]
Hey can you please remove the spam label from this request. I have made a valid merge request right?

**Comment by ujjwalshiva** [comment]
I thought GFG solutions were required. I didnt know about this. I will close the request. Can you please remove the label?

**Comment by khawajaazfar2000** [comment]
What is the source of your code?

**Pull request closed without merging**
