### PR TITLE
Create Quiz.py

### PR DESCRIPTION
**Pull request by shiva1217**

### CODE REVIEW

**Comment by khawajaazfar2000** [comment]
Error in line 15

**Comment by shiva1217** [comment]
I have rectified my mistake.
Kindly check it once.

**Comment by khawajaazfar2000** [comment]
How long have you being coding?
In you last code the only problem was two comma (' '), which make the (country of rising sun) unable to read my complier.
You write it as :
('Question 2: Which country is known as 'Country of Rising Sun'? ')
It suppose to be:
('Question 2: Which country is known as Country of Rising Sun? ')

**Comment by shiva1217** [comment]
Learning these stuffs.
Next year my intership period will start.So i am trying to learn as much as
i can.

**Comment by khawajaazfar2000** [comment]
Great, I'm merging it, keep up the hardwork. Also learn to debug by simplying reading what that error is saying , complier solves 80% of problem .
Good luck for interships.

**Comment by shiva1217** [comment]
Thank You Sir

**Pull request merged**
